[package]
name = "idna_adapter"
version = "0.0.0"
edition = "2021"
license = "Apache-2.0 OR MIT"
authors = ["Henri Sivonen <hsivonen@hsivonen.fi>"]
readme = "README.md"
description = "Back end adapter for idna"

[dependencies]
icu_normalizer = "1.4.3"
icu_properties = "1.4.2"

[features]
compiled_data = ["icu_normalizer/compiled_data", "icu_properties/compiled_data"]
