[package]
name = "idna_adapter"
version = "0.0.0"
edition = "2021"
license = "Apache-2.0 OR MIT"
authors = ["The rust-url developers"]
readme = "README.md"
description = "Back end adapter for idna"

[dependencies]
idna_mapping = { path = "../idna_mapping" }
unicode-bidi = { version = "0.3.10", default-features = false, features = ["hardcoded-data"] }
unicode-normalization = { version = "0.1.22", default-features = false }

[features]
compiled_data = []
